group=multibank
version=1.0.0
description=candle-aggregation-service

kotlin.code.style=official
org.gradle.caching=true
org.gradle.kotlin.dsl.allWarningsAsErrors=true
org.gradle.configuration-cache=true

javaTargetVersion=21
kotlinVersion=1.9.23

springBootVersion=3.3.5
springDependencyManagementVersion=1.1.5
springCloudVersion=2023.0.3
openapiGeneratorVersion=7.7.0
springdocOpenapiKotlinVersion=1.8.0
springDocOpenApiVersion=2.6.0
swaggerVersion=2.2.22
jibPluginVersion=3.4.3
liquibaseVersion=4.28.0
logbookVersion=3.9.0
kaptVersion=2.0.21
mapstructVersion=1.6.2
embeddedPostgresVersion=2.0.1
mockitoKotlinVersion=5.4.0
ktlintPluginVersion=12.2.0
